/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "7cac214d0f4b8e8e707a2a12aab8543ea4e0bdf1"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
