/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "4103ce089ac196ef7817d207ac19e54b8613a104"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
